-- USUÁRIOS
INSERT INTO usuarios (nome, senha) VALUES
('admin', '123'),
('joao', '123'),
('maria', '123');

-- ITEMS (lista)
INSERT INTO items (texto, userId) VALUES
('Obra A', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra B', 1),
('Obra C', 2),
('Obra D', 3);

-- COMENTÁRIOS
INSERT INTO comentarios (userId, texto, obraId, data) VALUES
(1, 'Comentário do admin na Obra A', 'Obra A', CURRENT_DATE),
(2, 'João comentou na Obra A', 'Obra A', CURRENT_DATE),
(3, 'Maria comentou na Obra B', 'Obra B', CURRENT_DATE),
(1, 'Admin comentou na Obra C', 'Obra C', CURRENT_DATE);
